### ISSUE TITLE
Make the chessboard responsive for mobile devices

### ISSUE THREAD

**Issue by programarivm** [programarivm/redux-chess#12]
At this moment the [demo](https://programarivm.com/demo-redux-chess/) is not being displayed properly on mobile devices.

**Comment by DenysLins** [comment]
I can help with this issue

**Comment by programarivm** [comment]
Thank you @DenysLins 

It seems as if this one will be about fine-tuning the [index.css](https://github.com/programarivm/redux-chess/blob/master/src/index.css) file, if I am not very much mistaken.

The following tutorial will be helpful:
- [How to Test a Local React NPM Package With Ease](https://javascript.plainenglish.io/testing-a-local-react-npm-package-with-ease-7d0668676ddb)

I can't wait to see what you come up with!

**Comment by programarivm** [comment]
Merged PR https://github.com/programarivm/redux-chess/pull/22
