### ISSUE TITLE
Remove the square click event when browsing the history

### ISSUE THREAD

**Issue by programarivm** [programarivm/redux-chess#20]
At this moment the chessboard squares can be clicked when browsing the history, which seems quite confusing. 

Also, the chessboard should be styled accordingly with CSS.

**Comment by nishit-prasad** [comment]
Hello! I'm new and would like to contribute. Can I take this up if it's available?

I am reviewing the docs but probably, I would need help/steps on how to reproduce and/or visualize it.

**Comment by programarivm** [comment]
Thank you @nishit-prasad,

This tutorial will guide you through setting the npm package up and running:

- [How to Test a Local React NPM Package With Ease](https://javascript.plainenglish.io/testing-a-local-react-npm-package-with-ease-7d0668676ddb) 

If you've got any questions please don't hesitate to ask.

Happy learning and coding, and keep it up!

**Comment by nishit-prasad** [comment]
Thank you! I really appreciate it!

**Comment by nishit-prasad** [comment]
Update: Apologies as I got caught up with work. Will be working on this and soon be updating my progress.

**Comment by programarivm** [comment]
thank you @nishit-prasad I'm looking at this one too which seems quite similar to https://github.com/programarivm/redux-chess/issues/42

**Comment by programarivm** [comment]
Merged PR https://github.com/programarivm/redux-chess/pull/46
