### ISSUE TITLE
Highlighting possible moves after a piece is clicked

### ISSUE THREAD

**Issue by programarivm** [programarivm/redux-chess#4]

**Comment by sayanh2** [comment]
want to contribute in this issue

**Comment by programarivm** [comment]
Thank you again @sayanh2 

It seems this issue is not too obvious if we want the frontend code to be lightweight as it is now for the time being. I'd say this one requires to add a new command on the [chess server](https://github.com/programarivm/chess-server). 

The following video shows the messages exchanged between the React app and the chess server.
   
https://user-images.githubusercontent.com/4062000/122679697-2baa4c00-d1ec-11eb-8ed7-f8d4def88638.mp4

**Comment by DenysLins** [comment]
Hi Guys. I think it is unnecessary to exchange messages with the server to implement this feature. You can hard-code each piece move in the frontend.

**Comment by programarivm** [comment]
thank you @DenysLins, if you want to have a look at this one it's been assigned to you as well as @sayanh2

**Comment by programarivm** [comment]
Merged PR https://github.com/programarivm/redux-chess/pull/39
