### ISSUE TITLE
Fix the browsing through history in 'Play with a friend' mode

### ISSUE THREAD

**Issue by programarivm** [programarivm/redux-chess#47]
When going back to the previous position the chessboard will go back two moves instead, as shown in the images below.

![Screenshot 2021-07-09 17:01:24](https://user-images.githubusercontent.com/4062000/125099808-b5a55080-e0d8-11eb-885b-b3d21dd6a388.png)
![Screenshot 2021-07-09 17:01:45](https://user-images.githubusercontent.com/4062000/125099831-bc33c800-e0d8-11eb-887f-eca54381ee80.png)

**Comment by IwonaBaran** [comment]
Can I try to fix this?

**Comment by programarivm** [comment]
Thank you @IwonaBaran, happy learning and coding! Keep it up.

**Comment by programarivm** [comment]
Just fixed this issue on the chess server https://github.com/programarivm/chess-server/commit/526cf98c4994f180bfca3499eedb209c6c2f4e66

**Comment by IwonaBaran** [comment]
Sorry about the delay in getting back to you. I had problems with connecting to the server. Need to learn more about this. I'm happy that the issue has been resolved now.

**Comment by programarivm** [comment]
Merged PR https://github.com/programarivm/redux-chess/pull/59
