### ISSUE TITLE
Add 'Play a friend' button

### ISSUE THREAD

**Issue by programarivm** [programarivm/redux-chess#7]
When clicking the button, a popup should be displayed showing the user a link to be shared with a friend.

For further information please visit:

- https://github.com/programarivm/chess-server/issues/1

- https://github.com/programarivm/chess-server/issues/3

**Comment by CHuante** [comment]
hi, id like to call dibs and take a crack at this and contribute if its still around?

**Comment by programarivm** [comment]
thank you @CHuante, I can't wait to see what you come up with!

**Comment by CHuante** [comment]
So for clarification, what should the button do? and where do you want it?

**Comment by programarivm** [comment]
The button should be somehow similar to "Play with a friend" button at https://lichess.org. 

It should be added to [components/Button](https://github.com/programarivm/redux-chess/blob/master/src/components/Buttons.js), which is a new component created a few hours ago.

For the sake of simplicity though we're creating a randomish token appended to an URL to be shared with a friend to play.

**Comment by programarivm** [comment]
@CHuante probably this issue is not too obvious since it implies some knowledge on the chess server actually. Sorry if it isn't a good first issue. 

If this is okay with you, please feel free to write a comment on https://github.com/programarivm/redux-chess/issues/10 so I can assign to you that one instead. 

See https://github.com/isaacs/github/issues/100

Thank you!

**Comment by programarivm** [comment]
Merged PR https://github.com/programarivm/redux-chess/pull/17
