### ISSUE TITLE
Allow to deselect a piece by clicking on any other of the player's pieces

### ISSUE THREAD

**Issue by programarivm** [programarivm/redux-chess#73]
For example, at this moment e2 can only be deselected by clicking on it again, as it is shown in the images attached.
![Screenshot 2021-07-23 19:49:10](https://user-images.githubusercontent.com/4062000/126822006-c4a819b4-13d4-46f0-b748-075150468e41.png)
![Screenshot 2021-07-23 19:51:19](https://user-images.githubusercontent.com/4062000/126822013-17ec630c-edb0-4652-916e-219fe0fd4192.png)

**Comment by masonwoodford** [comment]
Hello could I work on this?

**Comment by programarivm** [comment]
thank you @masonwoodford, happy learning and coding!

**Comment by masonwoodford** [comment]
I am sorry @programarivm but I think I am a little over my head with this one because of the lightweight nature and me being unfamiliar with PHP I am unsure of how to go about testing my effects on the code. Thank you for the opportunity though! I will unassign myself.

**Comment by programarivm** [comment]
Thanks for the feedback @masonwoodford if you'd want to have a look at this one within the next few days, there's a sandbox server up and running now as described in the README. Thank you!

**Comment by masonwoodford** [comment]
Cool thanks for that I'll try to look into this over the weekend!

**Comment by programarivm** [comment]
The full-stack project is quite challenging in reality.

If you feel like you want to look at an issue, probably it's a good idea to start looking at this one https://github.com/programarivm/redux-chess/issues/30 instead. The sandbox server is available now.

Remember, the secret to writing code with ease and joy is take one step at a time; for further information please visit:

- [My First Integration Test in a Redux Hooked App](https://programarivm.medium.com/)

Happy learning and coding!

**Comment by programarivm** [comment]
Merged PR https://github.com/programarivm/redux-chess/pull/86
